# Generated by Django 4.1.1 on 2022-09-25 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAPI', '0003_remove_todomodel_id_alter_todomodel_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='todo_name', max_length=512)),
                ('finished', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='ToDoModel',
        ),
    ]
