# Generated by Django 4.1.1 on 2022-09-25 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAPI', '0004_todoitem_delete_todomodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
